routes/web.php
<?php

use App\Content\Http\Controller\AddCommentToPostController;
use App\Content\Http\Controller\PostController;
use App\Media\Http\Controller\MediaController;
use Illuminate\Support\Facades\Route;


Route::get('/', [PostController::class, 'index']);

// Media
Route::group(['prefix' => 'media/tiny', 'as' => 'media.tiny.'], function () {
    Route::post('photo/upload', [MediaController::class, 'uploadTinyPhoto'])->name('photo.upload');
    Route::post('media/upload', [MediaController::class, 'uploadTinyMedia'])->name('media.upload');
    Route::post('file/upload', [MediaController::class, 'uploadTinyFile'])->name('file.upload');
});

// Posts
Route::resource('posts', PostController::class)->except(['show', 'create', 'edit']);
Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {

    Route::group(['as' => 'comments.'], function () {
        Route::post('{post}/comments', [AddCommentToPostController::class, 'store'])->name('store');
        Route::patch('comments/{comment}/update', [AddCommentToPostController::class, 'update'])->name('update');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/Article.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Article extends Component
{
    public $post;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($post)
    {
        $this->post = $post;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.app.article');
    }
}

app/View/Components/CommentInput.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class CommentInput extends Component
{
    public $post;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($post)
    {
        $this->post = $post;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.app.comment-input');
    }
}

app/View/Components/CommentSingle.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class CommentSingle extends Component
{
    public $comment;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($comment)
    {
        $this->comment = $comment;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.app.comment-single');
    }
}

app/View/Components/TextInput.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class TextInput extends Component
{
    public $name;
    public $title;
    /**
     * @var null
     */
    public $label_class;
    /**
     * @var null
     */
    public $input_class;
    /**
     * @var null
     */
    public $error_class;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($name,
                                $title,
                                $label_class = null,
                                $input_class = null,
                                $error_class = null)
    {
        $this->name        = $name;
        $this->title       = $title;
        $this->label_class = $label_class ?? 'form-label';
        $this->input_class = $input_class ?? 'form-control';
        $this->error_class = $error_class ?? 'invalid-feedback';
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.app.text-input');
    }
}

app/View/Components/TextareaInput.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class TextareaInput extends Component
{
    public $name;
    public $title;
    /**
     * @var null
     */
    public $label_class;
    /**
     * @var null
     */
    public $textarea_class;
    /**
     * @var null
     */
    public $error_class;
    /**
     * @var false
     */
    public $isTiny;
    /**
     * @var null
     */
    public $id;
    /**
     * @var null
     */
    public $placeholder;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($name,
                                $title,
                                $id = null,
                                $label_class = null,
                                $textarea_class = null,
                                $error_class = null,
                                $isTiny = false,
                                $placeholder = '')
    {
        $this->name           = $name;
        $this->title          = $title;
        $this->id             = $id ?? $name;
        $this->label_class    = $label_class ?? 'form-label';
        $this->textarea_class = $textarea_class ?? 'form-control';
        $this->error_class    = $error_class ?? 'invalid-feedback';
        $this->isTiny         = $isTiny;
        $this->placeholder    = $placeholder;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.app.textarea-input');
    }
}

resources/views/front/index.blade.php
@extends('front.layout.master')

@section('content')
	<main class="container-fluid">
		<div class="row">

			<div class="col-md-6">
				<div class="position-sticky" style="top: 0.5rem;">
					<div class="row flex-nowrap justify-content-between align-items-center">
						<div class="col-12 text-center">
							<a class="text-dark text-decoration-none fs-1"
							   href="#">@lang('actions.submit') @lang('blog.article')</a>
						</div>
					</div>

					<div class="row my-3 mb-2">
						<div class="col-12">
							<form action="{{ route('posts.store') }}" method="post">
								@csrf
								<div class="row">
									<div class="col-12">
										<x-text-input name="title" :title="__('blog.title')"/>
									</div>

									<div class="col-12">
										<x-textarea-input name="body" :title="__('blog.body')" :is-tiny="true"/>
									</div>
								</div>

								<button class="mt-4 w-100 btn btn-primary btn-lg"
										type="submit">@lang('actions.submit') @lang('blog.article')</button>

								<hr class="my-4">
							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="row flex-nowrap justify-content-between align-items-center mt-3">
					<div class="col-12 text-center">
						<a class="logo text-dark text-decoration-none fs-1" href="#">@lang('blog.blog')</a>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<hr>

						@forelse($articles as $post)
							<x-article :post="$post"/>
							<hr>
						@empty
							<p class="alert alert-warning text-center">@lang('blog.empty')</p>
						@endforelse

					</div>
				</div>
			</div>
		</div>
	</main>

@endsection

resources/views/front/layout/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	@include('front.layout.styles')
	@stack('styles')

	<title>NAK interview</title>

</head>
<body dir="rtl">

@yield('content')

@include('front.layout.scripts')
@stack('scripts')

</body>
</html>

resources/views/front/layout/scripts.blade.php
<script src="{{ mix('assets/js/script.js') }}"></script>

<script>
	var BATinymce = function (imgUrl, mediaUrl, fileUrl, csrf, maxImg, maxMedia, maxFile) {
		maxImg = (typeof maxImg !== 'undefined') ? maxImg : 3000;
		maxMedia = (typeof maxMedia !== 'undefined') ? maxMedia : 10000;
		maxFile = (typeof maxFile !== 'undefined') ? maxFile : 5000;
		var base_url = window.location.origin;
		var ele = $('.tiny');
		var topLevelWindow;
		if (ele.length > 0) {
			tinymce.init({
				selector: '.tiny',
				language: 'fa_IR',
				plugins: [
					'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
					'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime nonbreaking',
					'save table directionality template paste media'
				],
				toolbar1: 'undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent',
				toolbar2: 'styleselect | link unlink anchor | image media| forecolor backcolor | print preview code ',
				image_advtab: false,
				image_dimensions: false,
				media_dimensions: false,
				media_alt_source: false,
				automatic_uploads: true,
				directionality: 'rtl',
				relative_urls: false,
				remove_script_host: false,
				document_base_url: base_url,
				image_class_list: [
					{title: "Responsive", value: "img-fluid"}
				],
				file_picker_types: 'file image media',
				video_template_callback: function (data) {
					return '<video width="100%" height="auto" ' + (data.poster ? ' poster="' + data.poster + '"' : '') + ' controls="controls">\n' + '<source src="' + data.source + '"' + (data.sourcemime ? ' type="' + data.sourcemime + '"' : '') + ' />\n' + (data.altsource ? '<source src="' + data.altsource + '"' + (data.altsourcemime ? ' type="' + data.altsourcemime + '"' : '') + ' />\n' : '') + '</video>';
				},
				content_style: "body { font-family: 'IRANSans'; }",
				setup: function (editor) {
					editor.on('change', function () {
						editor.save();
					});
					editor.on('OpenWindow', function (eventDetails) {
						topLevelWindow = eventDetails.dialog;
					});
				},
				file_picker_callback: function (callback, value, meta) {
					function showUploadError(text) {
						console.log(text);
					}

					function showSizeError() {
						console.log(text);
					}

					function checkFileSize(file, size) {
						var fsize = Math.round((file.size / 1024));
						if (fsize >= size) {
							showSizeError();
							return false;
						}
						return true;
					}

					var input = document.createElement('input');
					input.setAttribute('type', 'file');

					// Provide file and text for the link dialog
					if (meta.filetype == 'file') {
						input.setAttribute('accept', '.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx');

						input.onchange = function () {
							var file = this.files[0];
							if (checkFileSize(file, maxFile)) {
								var xhr, formData;
								xhr = new XMLHttpRequest();
								xhr.withCredentials = false;
								xhr.open('POST', fileUrl);
								xhr.setRequestHeader("X-CSRF-Token", csrf);
								xhr.upload.onloadstart = function () {
									topLevelWindow.block("Uploading ...");
								};
								xhr.onload = function () {
									topLevelWindow.unblock();
									var json;
									if (xhr.status != 200) {
										if (xhr.status == 422) {
											json = JSON.parse(xhr.responseText);
											showUploadError(json.file);
										}
										callback('');
										return;
									}
									json = JSON.parse(xhr.responseText);

									if (!json || typeof json.location != 'string') {
										showUploadError('');
										callback('');
										return;
									}
									// call the callback and populate the Title field with the file name
									callback(json.location, {text: file.name});
								};
								formData = new FormData();
								formData.append('file', file);
								xhr.send(formData);
							}
						};
					}

					// Provide image and alt text for the image dialog
					if (meta.filetype == 'image') {
						input.setAttribute('accept', '.png,.jpg,.jpeg,.gif');

						input.onchange = function () {
							var file = this.files[0];
							if (checkFileSize(file, maxImg)) {
								var xhr, formData;
								xhr = new XMLHttpRequest();
								xhr.withCredentials = false;
								xhr.open('POST', imgUrl);
								xhr.setRequestHeader("X-CSRF-Token", csrf);
								xhr.upload.onloadstart = function () {
									topLevelWindow.block("Uploading ...");
								};
								xhr.onload = function () {
									topLevelWindow.unblock();
									var json;
									if (xhr.status != 200) {
										if (xhr.status == 422) {
											json = JSON.parse(xhr.responseText);
											showUploadError(json.file);
										}
										callback('');
										return;
									}
									json = JSON.parse(xhr.responseText);

									if (!json || typeof json.location != 'string') {
										showUploadError('');
										callback('');
										return;
									}
									// call the callback and populate the Title field with the file name
									callback(json.location, {alt: file.name});
								};
								formData = new FormData();
								formData.append('file', file);
								xhr.send(formData);
							}
						};
					}

					// Provide alternative source and posted for the media dialog
					if (meta.filetype == 'media') {
						input.setAttribute('accept', '.mp4,.mp3');

						input.onchange = function () {
							var file = this.files[0];
							if (checkFileSize(file, maxMedia)) {
								var xhr, formData;
								xhr = new XMLHttpRequest();
								xhr.withCredentials = false;
								xhr.open('POST', mediaUrl);
								xhr.setRequestHeader("X-CSRF-Token", csrf);
								xhr.upload.onloadstart = function () {
									topLevelWindow.block("Uploading ...");
								};
								xhr.onload = function () {
									topLevelWindow.unblock();
									var json;
									if (xhr.status != 200) {
										if (xhr.status == 422) {
											json = JSON.parse(xhr.responseText);
											showUploadError(json.file);
										}
										callback('');
										return;
									}
									json = JSON.parse(xhr.responseText);

									if (!json || typeof json.location != 'string') {
										showUploadError('');
										callback('');
										return;
									}
									// call the callback and populate the Title field with the file name
									callback(json.location, {title: file.name});
								};
								formData = new FormData();
								formData.append('file', file);
								xhr.send(formData);
							}
						};
					}

					input.click();
				}
			});
		}
	}

	BATinymce('{{route('media.tiny.photo.upload')}}',
		'{{route('media.tiny.media.upload')}}',
		'{{route('media.tiny.file.upload')}}',
		'{{csrf_token()}}',
		3000,
		10000,
		5000
	);
</script>

resources/views/front/layout/styles.blade.php
<link rel="stylesheet" href="{{ mix('assets/css/style.css') }}">